#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Wed Feb  8 20:33:38 2012

import wx

# begin wxGlade: extracode
from anzhelka_terminal import *
# end wxGlade



class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.label_3 = wx.StaticText(self, -1, "label_3 more label")
        self.label_1 = wx.StaticText(self, -1, "label_1 Big Label!")
        self.label_2 = wx.StaticText(self, -1, "label_2")
        self.label_4 = wx.StaticText(self, -1, "label_4")
        self.text_ctrl_1 = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY)
        self.button_2 = wx.Button(self, -1, "Pause")
        self.button_1 = wx.Button(self, -1, "Clear")
        self.checkbox_1 = wx.CheckBox(self, -1, "Hide Parsed Strings")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.handler_terminal_pause, self.button_2)
        self.Bind(wx.EVT_BUTTON, self.handler_terminal_clear, self.button_1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame_1")
        self.SetSize((725, 445))
        self.checkbox_1.SetValue(1)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1 = wx.FlexGridSizer(6, 1, 10, 10)
        grid_sizer_2 = wx.FlexGridSizer(1, 3, 0, 10)
        grid_sizer_1.Add(self.label_3, 0, 0, 0)
        grid_sizer_1.Add(self.label_1, 0, 0, 0)
        grid_sizer_1.Add(self.label_2, 0, 0, 0)
        grid_sizer_1.Add(self.label_4, 0, 0, 0)
        grid_sizer_1.Add(self.text_ctrl_1, 0, wx.EXPAND, 0)
        grid_sizer_2.Add(self.button_2, 0, 0, 0)
        grid_sizer_2.Add(self.button_1, 0, 0, 0)
        grid_sizer_2.Add(self.checkbox_1, 0, 0, 0)
        grid_sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)
        grid_sizer_1.AddGrowableRow(4)
        grid_sizer_1.AddGrowableCol(0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def handler_terminal_pause(self, event): # wxGlade: MyFrame.<event_handler>
        print "new handler information..."
        event.Skip()

    def handler_terminal_clear(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `handler_terminal_clear' not implemented!"
        event.Skip()

# end of class MyFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    main_frame = MyFrame(None, -1, "")
    app.SetTopWindow(main_frame)
    main_frame.Show()
    app.MainLoop()
